# SekaiOS — GSettings 를 못 읽는 경우의 대비책
[Settings]
gtk-application-prefer-dark-theme=1
gtk-icon-theme-name=Papirus-Dark
gtk-cursor-theme-name=DMZ-White
gtk-cursor-theme-size=24
gtk-font-name=Pretendard 10
gtk-decoration-layout=:minimize,maximize,close
